language: php

php:
  - 7.0

sudo: false

cache:
  directories:
  - $HOME/.composer/cache

services:
  - docker

before_install:
  - php -r "touch('./database/database.sqlite');"

install:
  - cp .env.example .env
  - travis_retry composer install --no-interaction
  - php artisan key:generate

before_script:
  - phpenv config-rm xdebug.ini # disabling XDebug as currently we are not interested in code coverage report

script: 
  # - ./vendor/bin/parallel-lint --exclude vendor .
  - php artisan view:clear
  # - ./vendor/bin/php-cs-fixer fix --dry-run
  - composer run install-video-cli
  - chmod +x ./bin/bin/packager-linux
  - php artisan config:clear
  - vendor/bin/phpunit && docker build -t k-video-streaming .

notifications:
  email:
    on_success: never